# Generated by Django 5.2.6 on 2025-12-11 22:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount of money transferred.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_type', models.CharField(choices=[('Send', 'Send')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the transaction was created.')),
                ('from_wallet_balance_before', models.DecimalField(decimal_places=2, help_text="Sender's balance before the transaction.", max_digits=15)),
                ('to_wallet_balance_before', models.DecimalField(decimal_places=2, help_text="Receiver's balance before the transaction.", max_digits=15)),
                ('from_wallet', models.ForeignKey(help_text='The wallet from which the funds are sent.', on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(help_text='The wallet to which the funds are received.', on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('req_type', models.CharField(choices=[('Collect Money', 'Collect Money')], default='Collect Money', help_text='Type of collection request', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=60, null=True)),
                ('from_user', models.ForeignKey(help_text='The user who is requesting the money.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_collection_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='The user from whom the money is requested.', on_delete=django.db.models.deletion.CASCADE, related_name='received_collection_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_request', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Collection Request',
                'verbose_name_plural': 'Collection Requests',
                'db_table': 'collection_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
