# Generated by Django 5.2.6 on 2025-11-01 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallet', '0002_wallet_wallet_balance_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='collectionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='creq_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='collectionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='creq_from_to_distinct'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 1.0)), name='tx_amount_min_1_0'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('from_wallet', models.F('to_wallet')), _negated=True), name='tx_from_to_distinct'),
        ),
    ]
