# Generated by Django 5.2.6 on 2025-12-11 08:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, help_text='Maximum amount allowed in a single transaction.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('daily_limit', models.DecimalField(decimal_places=2, help_text='Maximum total amount allowed in a 24-hour period.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monthly_limit', models.DecimalField(decimal_places=2, help_text='Maximum total amount allowed in a calendar month.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this limit is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Limit',
                'verbose_name_plural': 'System Limits',
                'db_table': 'system_limits',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, help_text='Maximum amount allowed in a single transaction.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('daily_limit', models.DecimalField(decimal_places=2, help_text='Maximum total amount allowed in a 24-hour period.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monthly_limit', models.DecimalField(decimal_places=2, help_text='Maximum total amount allowed in a calendar month.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this limit is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='The user to which these personal limits apply.', on_delete=django.db.models.deletion.CASCADE, related_name='personal_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Limit',
                'verbose_name_plural': 'Personal Limits',
                'db_table': 'personal_limits',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='FamilyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_transaction_limit', models.DecimalField(decimal_places=2, help_text='Maximum amount allowed in a single transaction.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('daily_limit', models.DecimalField(decimal_places=2, help_text='Maximum total amount allowed in a 24-hour period.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monthly_limit', models.DecimalField(decimal_places=2, help_text='Maximum total amount allowed in a calendar month.', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this limit is active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(help_text='The child user to whom the limits apply.', on_delete=django.db.models.deletion.CASCADE, related_name='family_limit', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(help_text='The parent user setting the limits.', on_delete=django.db.models.deletion.CASCADE, related_name='family_limits_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Limit',
                'verbose_name_plural': 'Family Limits',
                'db_table': 'family_limits',
                'abstract': False,
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
