# Generated by Django 5.2.6 on 2025-10-14 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('transaction_limit', models.DecimalField(decimal_places=2, default=5000.0, max_digits=15)),
                ('max_limit', models.DecimalField(decimal_places=2, default=20000.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Wallet',
                'db_table': 'Wallet',
            },
        ),
    ]
