# Generated by Django 5.2.6 on 2025-09-23 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'db_table': 'Families',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('national_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child'), ('User', 'User')], default='User', max_length=10)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('lock_time', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=10)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.family')),
                ('wallet_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'Person',
            },
        ),
    ]
