name: Sync to GitLab

on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.email "sondos.wael2025@gmail.com"
          git config --global user.name "27Swa"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@git.et3.co/et3/projects/internship-2025/CashBee.git
          git push gitlab main --force
